### ISSUE TITLE
Textbox component aan Storybook toevoegen

### ISSUE THREAD

**Issue by Rozerinay** [nl-design-system/rijkshuisstijl-community#1007]

**Comment by GerwinTerpstra** [comment]
Voor de Textbox component bestaat er nog geen storybook pagina. De component komt uit Utrecht dus de documentatie kan grotendeels uit Utrecht gehaald worden: [Utrecht Textbox Stories](https://nl-design-system.github.io/utrecht/storybook/?path=/docs/css_css-textbox--docs)

**Comment by JoeriRoijenga** [comment]
Alias aanmaken dat `<TextBox/>` `<TextInput/>` wordt.
