### ISSUE TITLE
Externe link component

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/rijkshuisstijl-community#448]
Waarschijnlijk het handigst een wrapper te maken van de Utrecht Link met jullie externe link functionaliteit als extra feature.

- Gebruik de <Icon> wrapper van Utrecht als je een externe link icoon hebt
- Let op de accessibility van icon, moet wel text-equivalent hebben
- `external` prop gebruiken (en weer doorgeven aan Utrecht Link) voor privacy en noreferrer enzo

`Link.tsx` aanmaken in deze component library voor React:

```tsx
import { Link as UtrechtLink, type LinkProps as UtrechtLinkProps } from '@utrecht/component-library-react/dist/css-module';

interface RhcLinkProps extends UtrechtLinkProps {
  externalLabel?: string;
}

export const Link = forwardRef(
  (({ externalLabel, ...restProps}: RhcLinkProps, ref: ForwaredRef<HTMLAnchorElement>) => <UtrechtLink {...restProps} ref={ref}>{restProps.external && <Icon role="img" aria-label={externalLabel}><ExternalIconSVG/></Icon>}{children}</Link>);
```

`index.ts`:

```tsx
export * from '@utrecht/component-library-react/dist/css-module';

// Overwrite some components
export { Link } from './Link';
```

Voorbeeld van een wrapper van UtrechtLink voor Next.js: https://github.com/frameless/strapi/blob/main/packages/ui/src/components/AdvancedLink/index.tsx

**Figma**
[Link component in NLDS - Rijksoverheid - Bibliotheek](https://www.figma.com/design/txFX5MGRf4O904dtIFcGTF/NLDS---Rijkshuisstijl---Bibliotheek?node-id=153-1056&t=9KlJWkn6GEOm2sN1-11) ✅ Ready

**Comment by AlineNap** [comment]
Zie feedback in link story: https://github.com/nl-design-system/rijkshuisstijl-community/issues/474#issuecomment-2332016801
