### ISSUE TITLE
Button component

### ISSUE THREAD

**Issue by Rerbun** [nl-design-system/rijkshuisstijl-community#455]
https://nl-design-system.github.io/utrecht/storybook-react/?path=/docs/react-button--docs

**Figma**
[Button component in NLDS - Rijksoverheid - Bibliotheek](https://www.figma.com/design/txFX5MGRf4O904dtIFcGTF/NLDS---Rijkshuisstijl---Bibliotheek?node-id=153-1138&t=9KlJWkn6GEOm2sN1-11) ✅ Ready

**Comment by sjimbonator** [comment]
https://github.com/nl-design-system/rijkshuisstijl-community/blob/main/packages/components-react/src/Button.tsx -> word niet meer gebruikt dus kan weg

**Comment by Rozerinay** [comment]
**Design review**

- De Icon only button heeft in Figma andere spacingwaarden dan de reguliere Button. Tegelijkertijd zie ik dat de Icon only button geen losse component is, maar een variant van de Utrecht-button met een aria-label. Is het mogelijk om voor de Icon only variant toch aparte spacingwaarden toe te kennen, of niet?

**Comment by Rozerinay** [comment]
Wijziging ziet er goed uit!
