### ISSUE TITLE
Accordion component

### ISSUE THREAD

**Issue by Rerbun** [nl-design-system/rijkshuisstijl-community#456]
AccordionProvider van Utrecht

**Figma**
[Accordion component in NLDS - Rijksoverheid - Bibliotheek](https://www.figma.com/design/txFX5MGRf4O904dtIFcGTF/NLDS---Rijkshuisstijl---Bibliotheek?node-id=1261-4784&t=9KlJWkn6GEOm2sN1-1) ✅ Ready

**Comment by Robbert** [comment]
Rozerin en Aline gaan kijken om deze te voorzien van Component tokens, geven updates in Slack.

**Comment by Rozerinay** [comment]
**Design review**

De opmaak van de accordion in Storybook wijkt af van die in Figma.

Figma: 
<img src="https://github.com/user-attachments/assets/6b4cfb9a-301f-495e-bafd-f1bad2d8e8bc" width="400">

Storybook: 
<img src="https://github.com/user-attachments/assets/65c9b7ad-cb81-4c8d-a036-da354a3224d4" width="400">

Het lijkt me verstandig om de design tokens te controleren en de verschillen te corrigeren. Ik merk verschillen op in spacing, kleur, border, enzovoort.

**Comment by Rozerinay** [comment]
Design review #2

Goed werk!

- Ik zie dat de font-weight van het label is overgenomen van de Button (`--_utrecht-button-appearance-font-weight: var(--utrecht-accordion-button-font-weight, inherit);`). In het ontwerp hebben we de font-weight token `rhc.font-weight.chosen-regular` gebruikt. Is het mogelijk om deze weight aan te houden? Of is het een best practice om de weight van de Button over te nemen? Dan passen wij het aan aan onze kant in Figma.
- Bij de focus state lijkt de border-bottom niet zichtbaar te zijn bij de buttons, behalve bij de onderste button. Kan dit nog worden opgelost?
![Image](https://github.com/user-attachments/assets/1fa1c183-f988-40ee-8676-9e8d9bd82a92)
