### ISSUE TITLE
Blockquote component (zie comment design review)

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/rijkshuisstijl-community#461]
**Figma**
[Blockquote in NLDS - Rijksoverheid - Bibliotheek](https://www.figma.com/design/txFX5MGRf4O904dtIFcGTF/NLDS---Rijkshuisstijl---Bibliotheek?node-id=1349-6340&t=9KlJWkn6GEOm2sN1-11)

**Comment by Rozerinay** [comment]
PR: https://github.com/nl-design-system/rijkshuisstijl-community/pull/506

**Comment by AlineNap** [comment]
Nieuwe feature request voor de blockqoute:

We willen graag dat het mogelijk is om de nieuwe variant van de blockqoute te maken en de oude van de Fijkshuisstijl. Hiervoor moeten de volgende tokens worden toegevoegd aan het component.

- utrecht/rhc/new.blockqoute.border-radius
- blockquote.border.color
- blockqoute.border-width

Daarnaast de mogelijkheid om wel of geen border aan bepaalde kanten te tonen, graag op basis van tokens zodat er van thema (oud/nieuw) geswitcht kan worden. Ik heb de verschillende varianten toegevoegd aan [figma](https://www.figma.com/design/txFX5MGRf4O904dtIFcGTF/NLDS---Rijkshuisstijl---Bibliotheek?node-id=16266-2230&node-type=section&t=1iS9qsJb3df9KPFz-11).

@Robbert heeft wellicht bovenstaande tokens al aan het utrecht component toegevoegd. Vraag of kijk of dat klopt, ze mogen sowieso op de utrecht code toegevoegd worden. De mogelijkheid om een border aan of uit te zetten en aan 1 kant een border-radius te hebben is wel Rijkshuisstijl specifiek.

En dan heb ik een vraag, hebben jullie de token `utrecht.blockquote.row-gap` toegevoegd aan het component? Of zit deze in het oorspronkelijke component van utrecht? 

![Image](https://github.com/user-attachments/assets/8ec887ae-491e-43b3-8a00-f699b48db050)

**Comment by AlineNap** [comment]
Een PR van mij met deze extra border tokens met een utrecht prefix is al gemerged. Gaat om deze: https://github.com/nl-design-system/rijkshuisstijl-community/pull/634

**Comment by AlineNap** [comment]
Feedback design review wordt verwerkt in: 
- [Blockqoute review feedback](https://github.com/nl-design-system/rijkshuisstijl-community/issues/770)
- [Keep ](https://github.com/orgs/nl-design-system/projects/59/views/1?filterQuery=keep&pane=issue&itemId=81762706&issue=nl-design-system%7Crijkshuisstijl-community%7C730)

**Comment by AlineNap** [comment]
### Design review 15 November

- 1 appereance van de block-quote is genoeg, die kan de betreffende Rijksorganisatie dan vervolgens stijlen naar wens doormiddel van de tokens. 
- Tokens die wij zelf toevoegen graag de pre-fix rhc geven voor het onderscheid. Dat zijn onder andere de tokens uit het bijgevoegde screenshot.

**Vragen**
- Ik zie dat er pakketjes zijn gemaakt om de verschillende varianten te creëren. Ik ben benieuwd hoe dit werkt. 
- Zit het ticket van [consistente oplossing keep](https://github.com/orgs/nl-design-system/projects/59/views/1?filterQuery=aline+&pane=issue&itemId=81762706&issue=nl-design-system%7Crijkshuisstijl-community%7C730) hierin? (Ga zo dit ticket bekijken).

**Opmerkingen**
- Als je tokens toevoegt is het fijn als je de type invult in de json. Dan komt het voor ons gelijk in de juiste categorie in token studio/ Figma.
```
},
        "border-start-start-radius": {
          "value": "3rem",
          "**type**": "borderRadius"
        },
``` 

![Image](https://github.com/user-attachments/assets/0a1dbf1f-8c96-4511-a7a8-4a0e961e0a41)
