### ISSUE TITLE
Checkbox + Checkbox group component

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/rijkshuisstijl-community#462]
**Figma**
- [Checkbox in NLDS - Rijkshuisstijl - Bibliotheek](https://www.figma.com/design/txFX5MGRf4O904dtIFcGTF/NLDS---Rijkshuisstijl---Bibliotheek?node-id=944-1535&t=9KlJWkn6GEOm2sN1-11) 
- [Checkbox group in NLDS - Rijkshuisstijl - Bibliotheek](https://www.figma.com/design/txFX5MGRf4O904dtIFcGTF/NLDS---Rijkshuisstijl---Bibliotheek?node-id=954-2226&t=9KlJWkn6GEOm2sN1-11)
- [Form field checkbox option in NLDS - Rijkshuisstijl - Bibliotheek](https://www.figma.com/design/txFX5MGRf4O904dtIFcGTF/NLDS---Rijkshuisstijl---Bibliotheek?node-id=1031-2917&t=dPgmwX5V8Kw5tPJC-11) 
- [Form field option label in NLDS - Rijkshuisstijl - Bibliotheek](https://www.figma.com/design/txFX5MGRf4O904dtIFcGTF/NLDS---Rijkshuisstijl---Bibliotheek?node-id=1031-3546&t=dPgmwX5V8Kw5tPJC-11)

**Comment by Rozerinay** [comment]
PR: https://github.com/nl-design-system/rijkshuisstijl-community/pull/502

**Comment by Rozerinay** [comment]
**Design review: Checkbox**

Bij de 'Disabled' en 'Invalid' state zie ik on hover dat de background-color verandert van kleur. Deze hoort dezelfde kleur te behouden.

**Comment by Rozerinay** [comment]
**Design review**

Checkbox group:
- Het Label ontbreekt bij deze component.

Form field checkbox: 
- De naam van deze component is 'Form field checkbox option'.
- Er is bij het label een `margin-block-end` toegevoegd, terwijl dit niet in design is aangegeven. Waar komt deze vandaan? Ik zie dat de component daardoor ook in hoogte groter is (38px).
- De gap is 12px. In design heeft het de spacing `rhc.space.100` (8px). 

Form field checkbox group:
- Er lijkt geen `row-gap` te zijn ingesteld. In plaats daarvan is er op het label een `margin-block-end` toegepast. Hiermee is het anders in design. 
- Waar komt de story [Status](https://rijkshuisstijl-community-git-feature-ch-81703b-nl-design-system.vercel.app/iframe.html?viewMode=docs&id=rijkshuisstijl-form-field-checkbox-group--docs#status) vandaan? Waarvoor hebben we deze nodig?
- Ik vermoed dat [Input dir](https://rijkshuisstijl-community-git-feature-ch-81703b-nl-design-system.vercel.app/iframe.html?viewMode=docs&id=rijkshuisstijl-form-field-checkbox-group--docs#input%20dir) anders hoort te heten.
