### ISSUE TITLE
Form field + Select / Textarea / Text input

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/rijkshuisstijl-community#463]
- Form field label
- Form field description
- Form field error message

**Figma**
- [Form field in NLDS - Rijksoverheid - Bibliotheek](https://www.figma.com/design/txFX5MGRf4O904dtIFcGTF/NLDS---Rijkshuisstijl---Bibliotheek?node-id=958-1925&t=9KlJWkn6GEOm2sN1-11) 
- [Select in NLDS - Rijksoverheid - Bibliotheek](https://www.figma.com/design/txFX5MGRf4O904dtIFcGTF/NLDS---Rijkshuisstijl---Bibliotheek?node-id=1130-3652&t=9KlJWkn6GEOm2sN1-11) 
- [Textarea in NLDS - Rijksoverheid - Bibliotheek](https://www.figma.com/design/txFX5MGRf4O904dtIFcGTF/NLDS---Rijkshuisstijl---Bibliotheek?node-id=969-2047&t=9KlJWkn6GEOm2sN1-11) 
- [Text input in NLDS - Rijksoverheid - Bibliotheek](https://www.figma.com/design/txFX5MGRf4O904dtIFcGTF/NLDS---Rijkshuisstijl---Bibliotheek?node-id=859-981&t=9KlJWkn6GEOm2sN1-11) 
- [Form field label in NLDS - Rijksoverheid - Bibliotheek](https://www.figma.com/design/txFX5MGRf4O904dtIFcGTF/NLDS---Rijkshuisstijl---Bibliotheek?node-id=851-898&t=9KlJWkn6GEOm2sN1-11) 
- [Form field description in NLDS - Rijksoverheid - Bibliotheek](https://www.figma.com/design/txFX5MGRf4O904dtIFcGTF/NLDS---Rijkshuisstijl---Bibliotheek?node-id=851-924&t=9KlJWkn6GEOm2sN1-11) 
- [Form field error message in NLDS - Rijksoverheid - Bibliotheek](https://www.figma.com/design/txFX5MGRf4O904dtIFcGTF/NLDS---Rijkshuisstijl---Bibliotheek?node-id=851-939&t=9KlJWkn6GEOm2sN1-11)

**Comment by Rozerinay** [comment]
PR: https://github.com/nl-design-system/rijkshuisstijl-community/pull/503

**Comment by Robbert** [comment]
`FormFieldTextbox` implementatie: https://github.com/nl-design-system/utrecht/blob/main/packages/component-library-react/src/FormFieldTextbox.tsx

**Comment by AlineNap** [comment]
Design review:

1. De focus outline heeft streepjes om text input en textarea, hoort solid te zijn. De utrecht focus tokens moeten nog toegevoegd worden aan de json vermoed ik? 
2. Bij focus hoort de border van de inputs van 1px naar 2px te gaan, dit gebeurd niet. `utrecht.textbox.focus` wordt daarvoor gebruikt. 
3. Select input is 44px hoog ipv 48px, `utrecht.pointer-target.min-size` ontbreekt nog in de design tokens. 
4. Waarom is het form-field-select en niet gewoon alleen select? Dit is anders dan bij Utrecht opgebouwd. Ik mis sowieso het losse component select.
5. Er zit [8px spacing](https://rijkshuisstijl-community-git-feature-te-acc556-nl-design-system.vercel.app/?path=/story/rijkshuisstijl-form-field-textarea--description) tussen het label en de description. Die hoort daar niet, moet 0 zijn. Is ook geen token voor geloof ik?
6. Error message icoon is gecentreerd. Dat hoort baseline van de tekst. 


![Image](https://github.com/user-attachments/assets/0c21e9e5-5c54-4d7e-ad0b-39a08448793e)

**Comment by AlineNap** [comment]
Daarnaast is de error message van utrecht eigenlijk niet toereikend als we een achtergrondkleur en border-radius willen en dat de message onder het invoerveld komt te staan ipv erboven.

**Comment by AdhamAH** [comment]
1. Ja geloof ik. Dit komt uit een style het `utrecht-focus-ring` denk ik.
2. Je hebt gelijk.IK ga kijken waarom
3. In figma is het `46px` maar in ieder geval het is minder bij 2. Er is een token `max-inline-size` voor de `width` in RHC project. Maar bij Utrecht er staat een token `min-block-size` die niet bij de RHC tokens staat. Misschien kan je dat aanpassen of ik als je wilt want ik ga veranderen maken.
4. Ja en als dat weg haalt dan er uit echt druk! Ik probeer altijd de Figma volgen. In de Figma er staat een `gap` van `8px`

Storybook zonder spacing
![Image](https://github.com/user-attachments/assets/4ad7c9c1-1c15-488e-acbc-ef6a7ecd6c7e)

Figma
![Image](https://github.com/user-attachments/assets/01bef0e2-7552-4547-9173-8243e48af096)

8px gap

![Image](https://github.com/user-attachments/assets/fd2cec2b-f2d0-49c5-a79b-c63b53b6d6bc)

Bij Utrecht staat deze tokens
```
 "margin-block-end": { },
        "padding-block-start": {},
        "padding-block-end": {},
        "padding-inline-start": {},
        "padding-inline-end": {}
```
en ik heb deze als volgen gezetten 
```
 "margin-block-end": {
          "value": "{rhc.space.100}",
          "type": "spacing"
        },
        "padding-block-start": {},
        "padding-block-end": {
          "value": "{rhc.space.100}",
          "type": "spacing"
        },
        "padding-inline-start": {},
        "padding-inline-end": {}
```
Laat me maar weten wat je wilt. Zal ik hun weg halen? 

5. "Force of habits" 😄  meestal schrijf ik `align-items: center;` wanner ik `flex` gebruikt. Ik ga weg halen. 
6. De bonus vraag moet `6` zijn 😄 . 
7. `Form-field-..." komt met label, error message, status,... etc. Bij Utrecht er is geen `Form Field Select` of `Form Field Textarea` geloof ik. Deze is de [Select component](https://nl-design-system.github.io/utrecht/storybook/?path=/docs/react_react-select--docs) 

@AlineNap @Rozerinay zal ik jullie in github mention bij de code waar ik denk dat jullie moet controleren?

**Comment by AlineNap** [comment]
1. Fix in [deze PR](https://github.com/nl-design-system/rijkshuisstijl-community/pull/616)
2. Fijn!
3. Fix in zelfde pr van punt 1
4. Tussen het label en de description zou het 0 moeten zijn. Daaropvolgend dan 8px voor tussen input en het label en description. Als ik het goed begrijp mist er in de code van utrecht een div om het label en description, klopt dat? 
5. Is dit niet standaard code van utrecht? 
6. ---
7. Utecht heeft [select](https://nl-design-system.github.io/utrecht/storybook/?path=/docs/css_css-select--docs) moeten wij die niet ook apart aanbieden? Ik zou form-field-select verwachten onder het form-field component zoals hier bij [utrecht](https://nl-design-system.github.io/utrecht/storybook/?path=/docs/css-form-field-checkbox-group--docs). Zij hebben daar alleen nu inderdaad geen story voor. 

@AdhamAH

**Comment by AdhamAH** [comment]
1. Approved!
2. Ik ga deze in de volgende PR probeer om repareren. Als er een token nodig zijn of iets moet veranderen, zal  ik je laten  weten
3. Merged!
4. Ik moet nog kijken. Ik laat je weten
5. Nee. Ik moest de icon zelf in de component van utrecht zetten [hier](https://github.com/nl-design-system/rijkshuisstijl-community/pull/586/files#diff-9c9f9ac238fd85b1120b4799218d83a5b03ff2439afc7b5c1cf9bf7aecdc7179R14).  Er is geen icoon in [Utrecht](https://nl-design-system.github.io/utrecht/storybook/?path=/docs/react_react-form-field-error-message--docs). Bij utercht je kan allen als `children` aanpassen. Ik dacht als ik ga Figma volgen dan moet ik permanent maken
6. _____________
7. Ik had hetzelfde idee! Form Field als hoofd component en de rest als sub componenten. Ik kan dat doen als het met @Robbert oke is.
@AlineNap

**Comment by AlineNap** [comment]
Topper! Leer weer meer over de opbouw van Utrecht componenten zo :) 

2. Goed om te weten! Even kijken hoe we die feedback bij utrecht en de community krijgen.
4. Ben benieuwd! 
5. again: goed om te weten. Figma klopt dus (nog) niet helemaal met Utrecht. 
7. Top! 

@AdhamAH
