### ISSUE TITLE
Form field radio group

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/rijkshuisstijl-community#464]
**Figma**
- [Radio group in NLDS - Rijkshuisstijl - Bibliotheek](https://www.figma.com/design/txFX5MGRf4O904dtIFcGTF/NLDS---Rijkshuisstijl---Bibliotheek?node-id=954-1910&t=9KlJWkn6GEOm2sN1-11) 
- [Form field radio option in NLDS - Rijkshuisstijl - Bibliotheek](https://www.figma.com/design/txFX5MGRf4O904dtIFcGTF/NLDS---Rijkshuisstijl---Bibliotheek?node-id=1039-2941&t=9KlJWkn6GEOm2sN1-11) 
- [Form field option label in NLDS - Rijkshuisstijl - Bibliotheek](https://www.figma.com/design/txFX5MGRf4O904dtIFcGTF/NLDS---Rijkshuisstijl---Bibliotheek?node-id=1031-3472&t=9KlJWkn6GEOm2sN1-11)

**Comment by Rozerinay** [comment]
PR: https://github.com/nl-design-system/rijkshuisstijl-community/pull/504

**Comment by Rerbun** [comment]
Geen styling voor description?

**Comment by Rozerinay** [comment]
@Rerbun 

Door die 8px margin onder het label, is de spacing tussen het label en de description te groot. 

Zouden we niet liever de Form field option label kunnen implementeren en gebruiken voor de Form field radio option en Form field checkbox option?

Nu hergebruiken we Form field label voor zowel labels bij Text input, Select etc., maar ook voor in de Radio group en Checkbox group.

**Comment by Rerbun** [comment]
Deze is terug naar ready gezet omdat er nog geen form field wrapper is voor de radio-group
