### ISSUE TITLE
Hero component

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/rijkshuisstijl-community#466]
Moet echt gerefined worden, er is nog veel onduidelijk. Deze component bestaat nog niet in de frontend ergens.

**Figma**
Hero in [NLDS - Rijkshuisstijl - Bibliotheek](https://www.figma.com/design/txFX5MGRf4O904dtIFcGTF/NLDS---Rijkshuisstijl---Bibliotheek?node-id=15708-524&node-type=CANVAS&t=Hno6L2BNkrA4sQOv-11) 

⚠️ Let op! Deze moeten we nog met de designers bespreken en voorzien van design tokens.

**Comment by Rozerinay** [comment]
Mees is nu bezig met de keep. Als dat ticket in 'Design review' staat, controleren wij in één keer ook de Hero.
