### ISSUE TITLE
Icon component

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/rijkshuisstijl-community#468]
Extra uitdaging, de Rijkshuisstijl icons zijn niet open source. We moeten een mapping gaan aanleggen van bestaande proprietary icon IDs naar open source icons.

- Voor functionele icons kunnen we Tabler icons gebruiken: https://tabler.io/icons
- Voor overheids-onderwerpen kunnen we https://Gemeenteniconen.nl gebruiken
- Icons die geen alternatief hebben moeten we Gebruiker Centraal en Martijn Rietveld lief aankijken

**Comment by Robbert** [comment]
- [ ] Maak een object met alle icon IDs van de Rijkshuisstijl iconenset. Waarschijnlijk heeft RVO die in de codebase staan: https://nl-design-system.github.io/rvo/?path=/docs/componenten-icon-icon-overview--docs

Laten we een iconenset aanbieden, van iconen met dezelfde ID als de officiele iconen die je in productie gebruikt. De iconen vullen we dan langzaam aan voor zover we ze nodig hebben. Functionele iconen zijn waarschijnlijk als eerste aan de beurt, en elleboognies als laatste.

bijvoorbeeld zoiets:

```tsx
import { IconHamburgerMenu } from '@tabler/icons-react';

const RijkshuisstijlIconID = 'menu' | 'meer' | 'elleboognies';
const IconenSet { [index: RijkshuisstijlIconID]: Icon } = {
  'menu': IconHamburgerMenu,
};
```

- [ ] Maak een Story aan met de <Icon> wrapper van utrecht met daarin een icoon naar keuze, uit deze iconset. Bijvoorbeeld een dropdown met `Object.keys(iconset)`

```tsx

import { Icon } from '@utrecht/...';
import { IconArrowLeft } from '@tabler/icons-react';


<Icon>< IconArrowLeft/></Icon>
```

**Comment by AlineNap** [comment]
Goed als wij dezelfde aanpak doen in Figma @Rozerinay. Dan bieden we via figma een biblotheek aan met alle iconen, dezelfde id namen als rijkshuisstijl zodat je die gemakkelijk kunt swappen. Dus twee bibliotheken met dezelfde component namen/ icoon-id's. 1 met de juiste rijkshuisstijl-iconen, die mag dan dus niet open source en 1 die dat nabootst. 

Wellicht met instructies voor Rijkshuisstijl designers hoe je zo'n biblotheek maakt met de juiste iconen en id's.

**Comment by Rozerinay** [comment]
@AlineNap goed punt. Ik heb deze taak met een aantal subtaken in onze to-do's geplaatst.
