### ISSUE TITLE
Heading 1 - Heading 6 en variable Heading

### ISSUE THREAD

**Issue by Rozerinay** [nl-design-system/rijkshuisstijl-community#469]
We kiezen ervoor om alleen de "Variable heading" component te exporteren en te documenteren:

https://nl-design-system.github.io/utrecht/storybook-react/?path=/docs/react-heading--docs

```tsx
<Heading level={1}>
  The Quick Brown Fox Jumps Over The Lazy Dog
</Heading>
```

**Figma**
[Heading component in NLDS - Rijksoverheid - Bibliotheek](https://www.figma.com/design/txFX5MGRf4O904dtIFcGTF/NLDS---Rijkshuisstijl---Bibliotheek?node-id=153-1039&t=9KlJWkn6GEOm2sN1-11) 🟡 In review

**Comment by Rozerinay** [comment]
@MeesD94 Heading ziet er goed uit!

Het enige wat ik me afvraag is waarom we Heading 6 tonen in Storybook, terwijl we hier geen gebruik van maken. Je ziet bijvoorbeeld dat de color daar anders is dan de overige Headings. Is het niet handiger om deze weg te laten, net zoals we in Figma hebben gedaan?

**Comment by AdhamAH** [comment]
ik ben niet zeker maar ik denk dat er twee optie `level` en `appearance`  zijn. `appearance` is voor de style en `level` for de `h` tag. Er zijn [6 levels](https://www.w3schools.com/tags/tag_hn.asp) van `h` tag. Daarom de 6de
Misschien kunnen de kleur en tokens voor het toegeven. Of als ik kan dat weg halen

**Comment by Rozerinay** [comment]
@AdhamAH ik zie dat [Amsterdam](https://designsystem.amsterdam/?path=/docs/components-text-heading--docs) ook maar 4 levels heeft gedefinieerd. Het lijkt me dus mogelijk om een level weg te laten, alhoewel ik bij 'sizes' wel weer level-6 zie staan. 

Wat bedoel je met 'Misschien kunnen de kleur en tokens voor het toegeven. Of als ik kan dat weg halen'?
