### ISSUE TITLE
Skip link

### ISSUE THREAD

**Issue by Rozerinay** [nl-design-system/rijkshuisstijl-community#471]
**Figma**
[Skip link in NLDS - Rijksoverheid - Bibliotheek](https://www.figma.com/design/txFX5MGRf4O904dtIFcGTF/NLDS---Rijkshuisstijl---Bibliotheek?node-id=2217-10122&t=9KlJWkn6GEOm2sN1-11)

- [ ] maak de Story met de skiplink
- [ ] zorg dat de skiplink zichtbaar is in Storybook by default, niet pas zichtbaar bij tabben (ik denk daar `utrecht-skip-link--visible` ofzo voor is)
- [ ] voeg de skiplink toe aan de templates, die moet linken naar `id="main"` met `href="#main`", en die moet uitkomen voorbij de navigatie zoals breadcrumb, maar direct bij de inhoud.
- [ ] de skiplink moet in de templates in de <header> element zitten. Niet in een `<nav>` stoppen.

**Comment by Rozerinay** [comment]
PR: https://github.com/nl-design-system/rijkshuisstijl-community/pull/510

**Comment by Robbert** [comment]
Voorbeeld van de skiplink story in Utrecht:
https://github.com/nl-design-system/utrecht/blob/7814d98cb8d8f35de250e10fb4686a7f9d0d6506/packages/storybook-css/src/SkipLink.stories.tsx

**Comment by Rozerinay** [comment]
**Design review**

Ziet er goed uit!

Wat is de reden dat er geen `box-block-end-shadow` is toegepast?
