### ISSUE TITLE
Invalid form alert

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/rijkshuisstijl-community#472]
Dit is gewoon een Alert

**Figma**
[Alert in NLDS - Rijksoverheid - Bibliotheek](https://www.figma.com/design/W0srM9b944eIjJb2vjs4Wz/NLDS---Rijksoverheid---Bibliotheek-(Community)?node-id=1179-3892&t=LWH2vwUBgPny4T4W-11) 🟡 In review

**Comment by Rozerinay** [comment]
PR: https://github.com/nl-design-system/rijkshuisstijl-community/pull/511

**Comment by AdhamAH** [comment]
PR #517

**Comment by Rozerinay** [comment]
**Design review**

- Voor de Heading is `rhc.font-size.heading.level-3 `gebruikt, in plaats van `rhc.font-size.heading.level-5`.
- Ik zie overigens dat je kunt switchen in het heading level. Waarom maken we dit mogelijk?
- Bij het versmallen van de viewport, schaalt de icoon mee. Die wordt erg klein. Dit hoort een fixed size te hebben.
