### ISSUE TITLE
Link

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/rijkshuisstijl-community#474]
Bestaat al in Storybook, kan misschien nog uitgebreid worden:
https://nl-design-system.github.io/rijkshuisstijl-community/?path=/docs/logius-link--docs

**Figma**
[Link component in NLDS - Rijksoverheid - Bibliotheek](https://www.figma.com/design/txFX5MGRf4O904dtIFcGTF/NLDS---Rijkshuisstijl---Bibliotheek?node-id=153-1056&t=9KlJWkn6GEOm2sN1-11) ✅ Ready

**Comment by AlineNap** [comment]
1. Icon size hoort {rhc.size.icon.functional} groot te zijn ipv 18px: hier een [PR](https://github.com/nl-design-system/rijkshuisstijl-community/pull/620) daarvoor.
2. Graag de active state toevoegen aan de stories zodat wij als designers de state kunnen reviewen
3. Het icoon van de external link veranderd niet naar de hover kleur, de andere iconen wel.

**Comment by AlineNap** [comment]
1. Fixed in [PR](https://github.com/nl-design-system/rijkshuisstijl-community/pull/620).
2. ? 
3. Done in [PR](https://github.com/nl-design-system/rijkshuisstijl-community/pull/626)
4. Feels done in bovenstaande PR.
5. Same
