### ISSUE TITLE
Paragraph

### ISSUE THREAD

**Issue by Rozerinay** [nl-design-system/rijkshuisstijl-community#475]
**Figma**
[Paragraph in NLDS - Rijksoverheid - Bibliotheek](https://www.figma.com/design/txFX5MGRf4O904dtIFcGTF/NLDS---Rijkshuisstijl---Bibliotheek?node-id=150-734&t=9KlJWkn6GEOm2sN1-11) ✅ Ready

**Comment by Rozerinay** [comment]
**Design review**

Ziet er goed uit! 

Eén vraag: waarom is de [small-print](https://www.figma.com/design/txFX5MGRf4O904dtIFcGTF/NLDS---Rijkshuisstijl---Bibliotheek?node-id=417-300&node-type=FRAME&t=gcUxCosSZ3Je47RX-11) variant weggelaten bij de stories? Deze komt wel voor bij Utrecht en in Figma. En [bovenaan de pagina](https://rijkshuisstijl-community-git-feature-fo-5778b0-nl-design-system.vercel.app/?path=/docs/rijkshuisstijl-paragraph--docs) is deze ook gedocumenteerd.

**Comment by AdhamAH** [comment]
Ik denk alleen Mees kan dat antwoorden. Maar ik kan dat toegeven.

**Comment by Rozerinay** [comment]
@AlineNap hebben we de small-print variant nodig? In dat geval kan Adham die toevoegen.
