### ISSUE TITLE
Action group / Button group component

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/rijkshuisstijl-community#479]
Voorstel: noem 'm ActionGroup. Skate where the puck is going to be.
https://nldesignsystem.nl/action-group/

https://nl-design-system.github.io/utrecht/storybook-react/?path=/docs/react-button-group--docs

Voorbeeld van hoe die toegepast wordt door RVO:
https://nl-design-system.github.io/rvo/?path=/docs/componenten-button-group--documentatie

RVO heeft ook nog wat tweaks om rechts uitlijnen mogelijk te maken, maar dat is niet recommended vanuit NL Design System voor gebruiksvriendelijkheid. Overleg even met Aline wat handig is voor de Rijkshuisstijl.

**Figma**
[Action group in NLDS - Voorbeeld - Bibliotheek ](https://www.figma.com/design/txFX5MGRf4O904dtIFcGTF/NLDS---Rijkshuisstijl---Bibliotheek?node-id=4626-10492&t=9KlJWkn6GEOm2sN1-11) 🟡 In review

**Comment by Rozerinay** [comment]
**Design review**

De Action group heeft in Figma een spacing van 0.5rem. In Storybook is dat echter 1rem. Kan dit worden aangepast?
