### ISSUE TITLE
Template: detail (zie comment design review)

### ISSUE THREAD

**Issue by Rerbun** [nl-design-system/rijkshuisstijl-community#519]

**Comment by Rerbun** [comment]
https://www.figma.com/design/H4hSqpPbvFMLklDZgswwgd/NLDS---Rijkshuisstijl---Templates?node-id=3085-5078&t=dIBesYtMvXxkEdRY-0

**Comment by Rozerinay** [comment]
Template is nog niet af. Graag kijken naar:

- de blokken waar een rode omlijning te vinden is. 
- de uitlijning.
- de spacings (margin-block-end).

**Comment by Rozerinay** [comment]
De spacings zijn nog niet correct verwerkt. 

Tussen Breadcrumb Navigation en Heading
<img width="353" alt="image" src="https://github.com/user-attachments/assets/f5ec36bb-bbb4-4826-bb62-404fd8d26214">

Tussen Heading en Link List en tussen Link List en Heading
<img width="300" alt="image" src="https://github.com/user-attachments/assets/9d53b4b4-9eed-46cb-aa09-4348f4c8fcb4">

Tussen Cards (op small viewport)
<img width="300" alt="image" src="https://github.com/user-attachments/assets/ebbbf9a3-0a33-4294-b29b-2d232f1359c5">

---

Er zit ook veel margin-block-end in de container van de cards (op small viewport).

<img width="300" alt="image" src="https://github.com/user-attachments/assets/38c4e23c-d868-4a80-b2f4-02866101cff0">

**Comment by Rozerinay** [comment]
**Design review 2**

Veel aanpassingen zijn correct doorgevoerd, netjes! Hieronder zijn de laatste puntjes voor verbetering te zien. 

---

De afbeelding in de Hero werkt niet. 

![Image](https://github.com/user-attachments/assets/fc5b173c-5100-4387-b34d-9d2131075caf)

---

De Link lijkt niet correct te zijn gestijld. Het zijn paarse linkjes in plaats van de reguliere blauwe linkjes.

![Image](https://github.com/user-attachments/assets/bb0518ee-ded4-4445-97b2-e864fd69c9d8)

---

Op large container is er 80px margin gebruikt om bij de page-content. Deze kan worden weggelaten, omdat de afstand te groot is.

![Image](https://github.com/user-attachments/assets/7e16f5c1-2d68-4a1f-bd87-6ff8e4b20309)

**Comment by Aref-Akminasi** [comment]
Dankjewel voor je feedback, Rozerin! Voor elk feedbackpuntje heb ik hieronder een kleine toelichting:

1. De afbeelding in de Hero werkt niet.
Opgelost: De afbeelding werkt nu. Dit was al in een andere taak opgelost.

2. Paarse linkjes in plaats van de reguliere blauwe linkjes.
Dit komt doordat de linkjes zich in de 'visited' state bevinden. Wanneer je een link bezoekt, verandert de kleur omdat alle linkjes naar # verwijzen. Dit betekent in feite 'dezelfde pagina', waardoor de browser denkt dat de link al is bezocht.
**Hoe kun je dit controleren?**
Open de template in een incognitovenster van je browser. In incognito zijn de linkjes nog niet bezocht en zouden ze blauw moeten zijn. In de praktijk komt dit goed, omdat de echte links in de uiteindelijke versie naar verschillende pagina's zullen verwijzen.

3. Op de large container is er 80px margin gebruikt.
Ik heb deze margin verwijderd.

**Comment by Rozerinay** [comment]
@Aref-Akminasi top! De template ziet er goed uit.
