### ISSUE TITLE
Navigation bar component

### ISSUE THREAD

**Issue by Rozerinay** [nl-design-system/rijkshuisstijl-community#555]
**Figma**
De Navigation bar is uitgebreid zodat het voldoet aan de mogelijkheden die voorkomen bij verschillende organisaties.

[Navigation bar in NLDS - Rijkshuisstijl - Bibliotheek](https://www.figma.com/design/Nv5EsCW9ioWBUSi9m9JqOa/Local---Rijkshuisstijl---Bibliotheek?node-id=1675-4140&t=7SCQhmq7RDkuHnvp-11) ⭕️

⚠️ Let op! Deze moeten we eerst nog intern en met de designers bespreken voordat het gebouwd mag worden.

**Comment by Robbert** [comment]
Dit is de `utrecht-nav-bar` en de `utrecht-nav-list` component samen. @Rerbun heeft al een beginnetje gemaakt om een vette demo te geven bij de Heartbeat, maar dit is eigenlijk nog niet opgepakt.

Zit al wel in de template, maar nog niet in Storybook. Design tokens kloppen waarschijnlijk ook nog niet.
