### ISSUE TITLE
Card component

### ISSUE THREAD

**Issue by Rozerinay** [nl-design-system/rijkshuisstijl-community#561]
[Card as link in Local - Rijkshuisstijl - Bibliotheek](https://www.figma.com/design/Nv5EsCW9ioWBUSi9m9JqOa/Local---Rijkshuisstijl---Bibliotheek?node-id=472-1420&node-type=CANVAS&t=aFryGnfIAneH0ddS-11) ⭕️

⚠️ Let op! Deze moeten we eerst nog intern en met de designers bespreken voordat het gebouwd mag worden.

Komt voor bij Rijksoverheid, Mijn Logius en RVO.

Card moet toegevoegd worden aan de details page.

#### Component

- [x] Component is beschikbaar in de index.
- [x] Design tokens worden gebruikt.

#### Storybook
- [x] Tenminste 1 default story.
- [x] States en properties stories.
- [x] Documentatie is toegepast, check template.

#### Tests
- [x] Het component rendert.
- [x] Tenminste de Basis functionaliteit van het component wordt getest.

**Comment by Rerbun** [comment]
terug naar in progress ivm nieuwe DODs

**Comment by veslav3** [comment]
@Rozerinay Ruben en ik hebben besloten deze pro-actief naar done te zetten. Mocht je nog willen kijken kun je het heropenen.
