### ISSUE TITLE
Demo pagina: Rich text pagina

### ISSUE THREAD

**Issue by MeesD94** [nl-design-system/rijkshuisstijl-community#564]
Deze story is af wanneer alle componenten op de demo pagina: Rich text Pagina, af zijn.

- [x] alle `unstarted` outlines zijn weg
- [ ] Design review en improvements (obviously, volgens sprint board): niet van Figma te onderscheiden
- [x] add footer

**Comment by MeesD94** [comment]
Footer added.

**Comment by Robbert** [comment]
De `href` ontbreekt van enkele button linkjes onderin, waardoor ze niet focusable zijn

**Comment by veslav3** [comment]
@AlineNap waar denk je dat dit de oplossing voor is?

> https://codefornl.slack.com/archives/C7KDQRXMZ/p1624449300092400?thread_ts=1624439600.088700&cid=C7KDQRXMZ
> 
> Mogelijke oplossing van Thomas voor nieuwe opzet?
