### ISSUE TITLE
Article

### ISSUE THREAD

**Issue by MeesD94** [nl-design-system/rijkshuisstijl-community#566]
https://nl-design-system.github.io/utrecht/storybook/?path=/docs/react_react-article--docs

**Comment by Robbert** [comment]
Hoi Roy, de enige design token die deze component heeft is article.max-inline-size. De bedoeling is om die in te stellen dat de tekstregel niet langer wordt dan de ideale lees-lengte, zo ongeveer 60-75 karakters.

**Comment by veslav3** [comment]
@Robbert ok, thanks voor de input.
