### ISSUE TITLE
Logo (zie comment design review)

### ISSUE THREAD

**Issue by Rerbun** [nl-design-system/rijkshuisstijl-community#567]
- Styling fixen (browser verschillen)
- Storybook

[Voorbeeld logo voor Rijksoverheid in Figma](https://www.figma.com/design/txFX5MGRf4O904dtIFcGTF/NLDS---Rijkshuisstijl---Bibliotheek?node-id=15465-3705&node-type=CANVAS&t=XS1b0sLOLDNrQwxX-11)
Dit is slechts een voorbeeld dat we kunnen inzetten voor de templates, omdat we niet het officiële logo mogen gebruiken.

**Comment by Rerbun** [comment]
Opnieuw geopend wegens nieuwe tokens: https://github.com/nl-design-system/rijkshuisstijl-community/pull/587

**Comment by Rerbun** [comment]
Logo moet worden omgebouwd, lint en icon kleur tokens omwisselen, updaten in templates

**Comment by AlineNap** [comment]
3 acties:

- De font-sizes kloppen niet helemaal heb hiervoor [nieuwe PR](https://github.com/nl-design-system/rijkshuisstijl-community/pull/665) ingeschoten. Deze graag goedkeuren. 
- Als de tekst over meerdere regels gaat verplaatst de tekst zich naar beneden, graag de token `rhc.wordmark.padding-block-start` toepassen .
- De laatste variant met + example icon van Nederland mag eruit.

**Comment by AlineNap** [comment]
### Design review 2:
- Graag naar de stijling van de design tokens luisteren die in de json staat. Stukje wat in de playground demo zit er dus afhalen. 
- Icon kunnen vervangen met rijkswapen en dat de positionering daarmee goed gaat. Wordt gefixt in: https://github.com/nl-design-system/rijkshuisstijl-community/issues/725. 

**Vraag:** 
Kunnen we design token documentatie toevoegen in ieder geval voor onze eigen componenten zoals het logo? Zoals utrecht heeft voor de componenten, [copy json](https://nl-design-system.github.io/utrecht/storybook/?path=/story/css_css-alert--design-tokens).

**Comment by AlineNap** [comment]
Er zit een max-width op de tekst. Is dat ergens op gebaseerd?
