### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by MeesD94** [nl-design-system/rijkshuisstijl-community#568]
Kijk naar de column layout van Utrecht

**Comment by Rozerinay** [comment]
**Design review**

- Ik zie bij een container van ±860px dat de 1e kolom waar de Link list in zit, naast de pay-off 'De Rijksoverheid…' wordt geplaatst. Is het toevallig mogelijk om deze kolommen onder elkaar weer te geven bij deze containergrootte, net zoals op een small container?
<img src="https://github.com/user-attachments/assets/d327b863-9fdb-469d-a2b1-d22c06c2c04f" width="300">

- Ik ben aan het zoeken naar waar de tokens voor `gap` en `column` vandaan komen. Deze zie ik niet terug in de Storybook van Utrecht. Waar zijn deze op gebaseerd? 

<img src="https://github.com/user-attachments/assets/d1c648bc-c83b-4ee4-a2ff-53a3ea731bbc" width="300">

**Comment by Rozerinay** [comment]
**Design review #2** 

- Zou je de breakpoint willen aanpassen naar 768px? Dan hebben we direct een logische breakpoint voor de tabletweergave.
- Ik denk dat door het verwijderen van de spacing tokens er geen ruimte meer is tussen de columns. Blijkbaar waren dit tokens die jullie handmatig hadden toegevoegd, en dat was helemaal prima! Ik vroeg me alleen af waar het vandaan kwam. Het lijkt me verstandig om die tokens weer toe te voegen. 
<img width="349" alt="image" src="https://github.com/user-attachments/assets/8674cf11-92a1-4441-bf8f-c196bcd0510f">

**Comment by MeesD94** [comment]
@Rozerinay Ik had voordat ik vakantie ging dit component gemaakt. Die column en gap tokens had ik inderdaad toegevoegd voor de ruimte tussen de kolommen. Ik pak dit componenten weer verder op en zal ze terug zetten en de verdere feedback toepassen :)
