### ISSUE TITLE
Fieldset

### ISSUE THREAD

**Issue by MeesD94** [nl-design-system/rijkshuisstijl-community#569]

**Comment by Rerbun** [comment]
Eerste PR hiervoor is klaargezet (#609), maar er is geen styling in Figma

**Comment by Rerbun** [comment]
RVO fieldset as reusable component

**Comment by Rerbun** [comment]
Fieldset section RVO

**Comment by Robbert** [comment]
Utrecht "Fieldset" met "section" flag voor background color:
https://nl-design-system.github.io/utrecht/storybook-css/?path=/story/css-form-fieldset--section

RVO Fielset:
https://nl-design-system.github.io/rvo/?path=/docs/componenten-form-fieldset--documentatie

**Comment by Rozerinay** [comment]
Aline maakt hier tokens voor aan. Verder krijgt de Fieldset dezelfde tokens als de Form Field. Dit is een tussenoplossing.

**Comment by AlineNap** [comment]
Qua stijling is die nu goed. Vooral nog vragen over de documentatie van dit element: https://codefornl.slack.com/archives/C01DAT4TRPF/p1729505233953249?thread_ts=1729243165.047769&cid=C01DAT4TRPF.
