### ISSUE TITLE
Side navigation component (zie comment design review)

### ISSUE THREAD

**Issue by Rozerinay** [nl-design-system/rijkshuisstijl-community#651]
Figma
[Side navigation in NLDS - Rijkshuisstijl - Bibliotheek](https://www.figma.com/design/txFX5MGRf4O904dtIFcGTF/NLDS---Rijkshuisstijl---Bibliotheek?node-id=1670-10258&node-type=canvas&t=h7nQ4VrpzSsXe21n-11)

**Comment by AdhamAH** [comment]
- Er is een bug met een plugin van Storybook. Maar zeker de focus werkt en als je `tab` drukt het moet werken.
- done
- done
- Het zelfde probleem als de eerste. Als je hard refresh doet dan de statuses gaan terug naar de juiste statuses. Deze ook gebeurt bij `checkbox` bijv.

Ik ga kijken een proberen de bug te oplossen

**Comment by veslav3** [comment]
> * Er is een bug met een plugin van Storybook. Maar zeker de focus werkt en als je `tab` drukt het moet werken. ![Image](https://private-user-images.githubusercontent.com/55054963/385651147-b0aa4903-e3f9-492e-b9ed-a8117e7e5ef7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMjkyMTQsIm5iZiI6MTczMjAyODkxNCwicGF0aCI6Ii81NTA1NDk2My8zODU2NTExNDctYjBhYTQ5MDMtZTNmOS00OTJlLWI5ZWQtYTgxMTdlN2U1ZWY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDE1MDgzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5ZjA4NmQyNzI3ZTNlMTFkYzIyMmJiNzBkOGJjMjgwNWYwYzgwYzE3NTVhZGU4YmY4OTcxMzA2MGJiNzMxZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.A6KzkD2Vpx8Ugvrf2BNc5OKyju5OthDZm0FWkKj43Bw)
> * done
> * done
> * Het zelfde probleem als de eerste. Als je hard refresh doet dan de statuses gaan terug naar de juiste statuses. Deze ook gebeurt bij `checkbox` bijv.
> 
> Ik ga kijken een proberen de bug te oplossen

@AdhamAH klikbare area van deze navbar links lijken mij erg groot. Is dat per design?
