### ISSUE TITLE
Number Badge/Counter Badge (zie comment design review)

### ISSUE THREAD

**Issue by AdhamAH** [nl-design-system/rijkshuisstijl-community#681]
https://www.figma.com/design/txFX5MGRf4O904dtIFcGTF/NLDS---Rijkshuisstijl---Bibliotheek?node-id=1233-4294&node-type=symbol&t=W7kpaMkoogPQzyYh-0

PR #679

**Comment by Rozerinay** [comment]
**Design review 1**

---

In Figma hebben we de Number Badge een vaste hoogte van 28px gegeven.

Deze hoogte is gebaseerd op de label width van 12px, met daarbovenop 8px `inline-padding`, wat optelt tot een totale width van 12 + 8 + 8 = 28px. Om de Number Badge als een perfecte cirkel weer te geven, moet de hoogte gelijk zijn aan de breedte, en daarom is deze ook op 28px gezet.

In de code is het nu 36px bij 36px. Kunnen we deze 28px bij 28px maken?

**Comment by AdhamAH** [comment]
Het problem is dat de `font-size` is `20px` daarom de `height`  gaat altijd `20px` zijn. En als ik de width naar `12px` zet, dan wordt het geen cirkel. En daarom het is 8+20+8=36

Ik kan de `font-size` naar `12px` zetten dan werkt het.Of ik zet de padding naar `4px`. Maar in ieder geval gaat er veranderen zijn in de style.

![Image](https://github.com/user-attachments/assets/a6b412ad-20ec-4bfc-8a0b-69a510191dae)


![Image](https://github.com/user-attachments/assets/4852521e-3515-430a-8205-1fcc93cb9497)

**Comment by AdhamAH** [comment]
Ook een notitie: de naam is nu Counter Badge in de Storybook. Ik heb deze badge gemaakt zodat je niet alleen een number kunt gebruiken, maar ook een string. Dit betekent dat je bijvoorbeeld een string zoals "Nieuw" kunt toevoegen. Als we de component als Number Badge willen houden, maak ik hem alleen geschikt voor numbers. Of ik kan de naam veranderen naar Data Badge, zodat zowel string als number ondersteund worden. ![Image](https://github.com/user-attachments/assets/74121fac-4192-47c8-a8d4-1a0c7d78b2bf)

**Comment by Rozerinay** [comment]
@AdhamAH je geeft aan dat de height van de Number Badge 20px wordt door de font size van 20px. Echter, door de token `utrecht.badge-counter.min-block-size` met de waarde `{voorbeeld.size.xs}`, is de minimale hoogte altijd 24px. Als we de width verlagen, dan kunnen we uitkomen op 24px bij 24px, toch?

En de [Number Badge](https://nldesignsystem.nl/number-badge) is enkel bedoeld voor aantallen, dus numerieke gegevens. Wat jij beschrijft, is de [Status Badge](https://nldesignsystem.nl/status-badge). Deze hebben we nog niet als component beschikbaar. Graag de Number Badge behouden en alleen geschikt maken voor cijfers.

**Comment by AdhamAH** [comment]
@Rozerinay ik ga de naam houden als `Number Badge` 
Nu heeft `utrecht.badge-counter.min-block-size`  `{rhc.size.half-lint}` en dat is ook `24px`. 
Je wilt dat de hele badge met de padding een width van `24px`, toch? dat kan niet met de `font-zise` van `20px`. Er is geen manier om te doen behalve wat ik heb al uitlegt

**Comment by JoeriRoijenga** [comment]
**Oplossing**
Alleen nog de naam aanpassen zoals hierboven genoemd door @AdhamAH
