### ISSUE TITLE
Design demo review: Fieldset-legend tokens toevoegen

### ISSUE THREAD

**Issue by Rozerinay** [nl-design-system/rijkshuisstijl-community#686]

**Comment by AlineNap** [comment]
Dit is niet de oplossing. Het radio button component is niet goed geïmplementeerd, je kunt nu alle radio buttons aanklikken. De radio buttons moeten nog gegroepeerd worden met het component radio group. Daarnaast zou niet de legend van de fieldset gebruikt moeten worden als label maar het form-label. 

Hoe die precies in de code zit weet ik niet. Daar gaat Robbert deze week ook aan werken als goed is.
