### ISSUE TITLE
Design demo review: Page-content background-color fix

### ISSUE THREAD

**Issue by Rozerinay** [nl-design-system/rijkshuisstijl-community#687]

**Comment by veslav3** [comment]
@Rerbun comment achtergelaten: https://github.com/nl-design-system/rijkshuisstijl-community/pull/787#issuecomment-2444571784

**Comment by Rerbun** [comment]
Issue is te onduidelijk, er zijn verschillende dingen gefixt in #792, maar code die geschreven wordt in referentie naar deze issue kan niet worden gereviewd
