### ISSUE TITLE
Border radius tokens voor Hero en Blockquote

### ISSUE THREAD

**Issue by Rerbun** [nl-design-system/rijkshuisstijl-community#724]
Volg figure als voorbeeld om hoekjes rond te maken via de tokens

**Comment by JoeriRoijenga** [comment]
Dit taakje is afhankelijk van #748, kan pas verder worden opgepakt als #748 is afgerond.

**Comment by JoeriRoijenga** [comment]
Dit taakje is gesloten en de feedback wordt in #770  en #771  meegenomen.
