### ISSUE TITLE
RHC template form pagina witte achtergrond

### ISSUE THREAD

**Issue by veslav3** [nl-design-system/rijkshuisstijl-community#738]
Figma: https://www.figma.com/design/H4hSqpPbvFMLklDZgswwgd/NLDS---Rijkshuisstijl---Templates?t=Qy2Val44vAiXfAkk-0

![Image](https://github.com/user-attachments/assets/642518e8-c82c-49c1-bb53-fce5d72a94c6)

**Comment by AlineNap** [comment]
Visueel klopt het ticket. 
Ik zou graag willen zien dat het gedaan wordt op basis van tokens, hier komen nieuwe tickets en/of componenten voor.
