### ISSUE TITLE
CSS laadt verschillend in templates tegenover storybook

### ISSUE THREAD

**Issue by Rerbun** [nl-design-system/rijkshuisstijl-community#772]
(dit voorbeeld is tegen de tijd dat deze issue is opgepakt gefixt en is niet meer relevant, maar is wel een duidelijk voorbeeld voor dit issue)
1. Open [form template](https://rijkshuisstijl-community-templates-git-9b1d00-nl-design-system.vercel.app/form) en [fieldset storybook](https://rijkshuisstijl-community-git-aline-fiel-9802f4-nl-design-system.vercel.app/?path=/story/rhc-fieldset--default) pagina's
2. Inspect fieldset legend in beide pagina's
3. Zie hoe de CSS in verschillende volgordes wordt ingeladen, hierbij is het in de storybook juist en in de templates onjuist

**Comment by JoeriRoijenga** [comment]
Het probleem is dat in NextJS de styling/CSS anders wordt ingeladen dan via Storybook. Dit zorgt voor inconsequent gedrag wat niet wenselijk is.

Op het moment wordt NextJS omgegooid om de templates in Storybook te gaan tonen. Dit wordt op het moment in #783 aangepast en kan er mogelijk voor zorgen dat het probleem zichzelf oplost.

Tbc...

**Comment by veslav3** [comment]
Als het goed is hebben we dit gefixt, we moeten nu controleren of het is opgelost.

**Comment by AdhamAH** [comment]
Ik denk ook deze PR #893 zorgt dat er geen problemen met CSS is. De zelfde style sheet nu wordt gebruikt in beide Next.js en Storybook. Ik denk dat er geen probleem is
