### ISSUE TITLE
Refactor component properties

### ISSUE THREAD

**Issue by JoeriRoijenga** [nl-design-system/rijkshuisstijl-community#788]
Heel veel expliciete properties in onze componenten zijn niet nodig om expliciet te definiëren, omdat de properties al in het component zitten dat wordt ge-extend, de properties zitten dan impliciet in de {...restProps}. 

Doel van deze story is dat dit wordt opgeschoond, zodat de code beter onderhoudbaar en leesbaarder is, zonder dat de functionaliteit verloren gaat.

Voorbeeld commit: https://github.com/nl-design-system/rijkshuisstijl-community/pull/768/commits/8089af89a75cf76634e438b992f959cd9ccfa334

**Comment by veslav3** [comment]
Heeft merge conflicts met de `main` branch, ga ik oplossen.
