### ISSUE TITLE
CSS laadt verschillend in chromatic tegenover storybook

### ISSUE THREAD

**Issue by Rozerinay** [nl-design-system/rijkshuisstijl-community#795]
De chromatic styling matcht niet met de styling in storybook
Bijvoorbeeld Accordion: in chromatic heeft deze grote spacing en is hij bold, in storybook niet
https://www.chromatic.com/test?appId=66c4849439813a13c602ebb1&id=6718b23913257cf077e9f2d6
https://66c4849439813a13c602ebb1-dylirvnxuq.chromatic.com/?path=/story/rhc-accordion--default

Storybook:
https://rijkshuisstijl-community.vercel.app/?path=/story/rhc-accordion--default

**Comment by JoeriRoijenga** [comment]
Het probleem lijkt zich voor te doen waarbij de styling initieel niet correct wordt ingeladen. Wanneer je vervolgens rond gaat klikken of over linkjes gaat hoveren, dan wordt de styling correct ingeladen. Chromatic voert in de eerste seconden na het inladen van de pagina de snapshot uit, waardoor de styling van een component wel correct kan zijn, maar niet correct wordt getoond in de tests.

**Oplossing richting**
Mogelijk kijken of het initieel inladen van de CSS correct kan plaatsvinden...
