### ISSUE TITLE
Component feature request: Preview van ingevoerde bestanden voor file-input (zie comment design review)

### ISSUE THREAD

**Issue by MeesD94** [nl-design-system/rijkshuisstijl-community#803]
Feature request: 

Graag de mogelijkheid om bestanden te "previewen" als deze zijn ingevoerd in het `file-input` component zodat de user kan controleren of het juiste bestand is geüpload. 

De bestandsnaam wordt dan een link waarop kan worden geklikt. Als er op is geklikt opent het bestand zich lokaal op de device van de gebruiker. 

![Image](https://github.com/user-attachments/assets/f2e79662-e505-42f8-8412-60071eedeb34)

**_Graag ook even accessibility checken._**

**Comment by Rozerinay** [comment]
@Rozerinay zoekt ook even uit wat wenselijk is voor design.

**Comment by GerwinTerpstra** [comment]
PR: https://github.com/nl-design-system/rijkshuisstijl-community/pull/804

**Comment by GerwinTerpstra** [comment]
[#1006](https://github.com/nl-design-system/rijkshuisstijl-community/pull/1006)
