### ISSUE TITLE
Inventarisatie Template RVO

### ISSUE THREAD

**Issue by JoeriRoijenga** [nl-design-system/rijkshuisstijl-community#807]
Op het moment is het niet duidelijk welke componenten het template omvatten. Hiervoor moet een inventarisatie plaatsvinden om duidelijk te krijgen welke componenten moet worden afgerond.

Taken:
- [x] 1. Welke componenten zijn er nodig?
- [x] 2. Welke componenten ontbreken nog?
- [x] 3. Welke componenten zijn nog niet af?
- [x] 4. Maak issues aan voor componenten die ontbreken/niet af zijn.
- [x] 5. Maak template aan om deze op basis van de componenten te gaan bouwen ([voorbeeld](https://github.com/orgs/nl-design-system/projects/59/views/1?filterQuery=rich&pane=issue&itemId=72856481&issue=nl-design-system%7Crijkshuisstijl-community%7C460)). 

[Figma link.](https://www.figma.com/design/H4hSqpPbvFMLklDZgswwgd/NLDS---Rijkshuisstijl---Templates?node-id=4663-21130&t=0t9JqRZiaTFDQtVr-11)

**Comment by veslav3** [comment]
Components die nodig zijn
- Page Header ✅
- Navbar ✅
- Hero ✅
- Heading 2 ✅
- Card ❌
- Card container ❌
- List ❌
- Footer ✅
