### ISSUE TITLE
REMOVE: Paragraph small-prop

### ISSUE THREAD

**Issue by JoeriRoijenga** [nl-design-system/rijkshuisstijl-community#965]
**Context**
Het Paragraph component bevat een tweetal props:
- `lead`
- `small`
De `lead` doet keurig wat het moet doen, maar de `small` daarentegen niet. De styling voor de gebruiker veranderd niet.

**Probleem**
Het probleem lijkt niet in de logica van het component te zitten, maar in de styling van het component zelf. De css-class veranderd namelijk van:
- `utrecht-paragraph`
Naar:
- `utrecht-paragraph__small`

**Oplossingsrichting**
Voeg juiste styling toe voor de `small` property.

**Comment by JoeriRoijenga** [comment]
Dit is niet meer relevant. Afgelopen Open Hour heeft Robbert aangegeven dat de `small` attribute verwijderd is omdat deze niet werd gebruikt. Aangezien deze niet bij ons werkt is dus ook besloten deze tot nadere orde niet meer te gebruiken. 

https://nldesignsystem.nl/paragraph

Dit taakje mag focus leggen op het verwijderen van de small attribute zodat deze niet meer gebruikt kan worden binnen ons component.

**Comment by JoeriRoijenga** [comment]
Onze code is niet geheel geschikt voor het verwijderen van de `small` attribute. De documentatie is vanuit Utrecht opgehaald waar het ook spreekt over `small` als optie. Daarnaast is onze code zo dat wij het component direct importeren en daarna weer exporteren.

Makkelijkste oplossing zonder onnodige extra code is een CSS class toevoegen die de `small` functioneel maakt. 

Gefixt in deze [PR](https://github.com/nl-design-system/rijkshuisstijl-community/pull/1017).

**Comment by Rozerinay** [comment]
@JoeriRoijenga korte vraag: Ik zie in de code dat de font-size van de variant Small op `inherit` staat. Ik ging ervan uit dat die de waarde van de variant Paragraph zou overnemen, maar dat blijkt niet het geval, aangezien de font-size kleiner is dan die van de Paragraph. Welke font-size wordt nu precies gebruikt voor de Small variant?

**Comment by JoeriRoijenga** [comment]
Dat zal gaan om `1.125rem` gebaseerd op [deze variabele](https://github.com/nl-design-system/rijkshuisstijl-community/blob/4e865fe781cbbac257baa6f31ecff1a854599807/proprietary/design-tokens/figma/figma.tokens.json#L734-L737)
