### ISSUE TITLE
PageHeader story toevoegen

### ISSUE THREAD

**Issue by JoeriRoijenga** [nl-design-system/rijkshuisstijl-community#970]
**Content**
Op het moment is er geen story in Storybook aanwezig voor `PageHeader`, maar we hebben het component wel in onze library en exporteren deze ook naar eindgebruikers.

**Oplossing**
Voeg een story toe voor `PageHeader`

**Comment by GerwinTerpstra** [comment]
https://github.com/nl-design-system/rijkshuisstijl-community/pull/1030
