### ISSUE TITLE
Nieuwsbrief: Rijkshuisstijl Community in het zonnetje (max. 30 min!)

### ISSUE THREAD

**Issue by Rozerinay** [nl-design-system/rijkshuisstijl-community#972]
Het einde van het jaar nadert, en dat is het perfecte moment om terug te kijken op de afgelopen maanden.

We willen graag de Rijkshuisstijl Community in het zonnetje zetten. Jullie inzet, harde werk en de prachtige resultaten die zijn behaald, verdienen onze waardering en een moment van reflectie.

Daarom schrijven we een korte bijdrage voor de nieuwsbrief van het NL Design System, om stil te staan bij wat we samen hebben bereikt.

Als hulpmiddel heb ik hieronder een setje vragen toegevoegd die je kunt gebruiken als input. Hoeft niet, mag wel.

- Waar ben jij het meest trots op wat je hebt bereikt in dit project?
- Welk moment was volgens jou een hoogtepunt tijdens de community sprint?
- Wat vond je het leukste of meest waardevolle aspect van dit project?
- Hoe zou je de samenwerking binnen het team omschrijven?
- Welke nieuwe dingen heb je geleerd tijdens dit project?
- Wat hoop je dat de community volgend jaar oppakt of verder uitbreidt?

**Comment by veslav3** [comment]
Wat ik echt geweldig vind aan dit project, is hoe we in zo’n korte tijd iets fantastisch hebben neergezet! Via de heartbeat de presentaties geven was een unieke kans om ons werk te laten zien waar we echt trots op zijn. De Design System Week was een enorme eye-opener; ik heb superveel geleerd en nieuwe inzichten opgedaan. De gezellige borrel na afloop maakte het helemaal af – wat een fijne sfeer! Het is ook prachtig om te zien hoeveel manieren er zijn om elkaar te ontmoeten binnen het NL Design System. Vooral de Estafette Model Dag is een topper: samenwerken met verschillende mensen en samen kwalitatieve, indrukwekkende componenten creëren – dat maakt het werken aan de Rijkshuisstijl community binnen NL design system helemaal af!

**Comment by Aref-Akminasi** [comment]
Als team hebben we onszelf veel ontwikkeld en gegroeid binnen het project, en we hebben een sterke impact gemaakt. Een hoogtepunt tijdens de community sprint was de samenwerking met het kernteam van NL Design System aan het estafettemodel, wat zeer waardevol en leerzaam bleek. Binnen ons zelfsturende team van Quintor werkten we effectief samen door elke sprint een retrospective te houden en een scrummaster aan te wijzen. Tijdens dit project kwam het belang van langetermijnbeslissingen en het snel onboarden van nieuwe collega’s duidelijk naar voren. De hoop is om binnenkort de templates live te zien bij overheidsinstanties.
